import Link from 'next/link'
const cases=[['Stone Island Jacket','89 000 ₽','46 000 ₽','−48%'],['Wooting 80HE','32 000 ₽','24 500 ₽','−23%'],['Lamzu Maya X','16 000 ₽','11 900 ₽','−25%']]
export default function Home(){return <main className="container grid">
 <section className="hero">
  <div className="card"><span className="badge blue">Персональный шопинг-сервис</span><h1>Мы найдём нужную вещь по фото или ссылке</h1><p className="muted">От брендовой одежды до компьютерной периферии — INNER ищет товары по лучшей цене, проверяет продавцов и показывает финальную стоимость до оплаты.</p><div className="row" style={{marginTop:24}}><Link className="btn" href="/request">Отправить заявку</Link><Link className="btn secondary" href="/track">Проверить заявку</Link></div><div className="grid grid3" style={{marginTop:34}}><div className="stat"><b>500+</b><p className="muted">обработанных заявок</p></div><div className="stat"><b>7–14</b><p className="muted">дней доставка</p></div><div className="stat"><b>0 ₽</b><p className="muted">скрытых комиссий</p></div></div></div>
  <div className="card soft"><h2>Каждая заявка под контролем</h2><p className="muted">Отправили фото — видите статус. Нашли варианты — выбираете подходящий. Заказали — отслеживаете доставку.</p><div className="notice"><b>#1248 Stone Island Jacket</b><p><span className="badge green">Найдены варианты</span></p><p className="muted">3 предложения · экономия до 48% · доставка 5–7 дней</p></div></div>
 </section>
 <section className="grid grid4"><div className="card"><h2>Одежда и обувь</h2><p className="muted">Бренды, редкие модели, ресейл и новые коллекции.</p></div><div className="card"><h2>Аксессуары</h2><p className="muted">Сумки, очки, украшения и часы.</p></div><div className="card"><h2>Периферия</h2><p className="muted">Мышки, клавиатуры, наушники, коврики и мониторы.</p></div><div className="card"><h2>Редкие товары</h2><p className="muted">Найдём то, что сложно купить напрямую.</p></div></section>
 <section className="card"><h2>Недавние находки</h2><div className="grid grid3">{cases.map(([n,oldp,p,s])=><div className="card soft" key={n}><h3>{n}</h3><p className="muted">Цена в РФ: <s>{oldp}</s></p><p><b>{p}</b> <span className="badge green">{s}</span></p><Link className="btn secondary" href={`/request?item=${encodeURIComponent(n)}&budget=${encodeURIComponent(p)}`}>Хочу похожую вещь</Link></div>)}</div></section>
 <section className="card"><h2>Как формируется цена</h2><p className="muted">Цена товара + доставка + комиссия сервиса + возможные пошлины = финальная стоимость до оплаты. Расчёт предварительный, финальную стоимость менеджер INNER фиксирует до оплаты.</p></section>
 </main>}
